[global]
UIName = Ultimate Apocalypse Soulstorm Campaign
Description = The Apocalypse project, developed by the Apocalypse mod team.
DllName = DXP3Mod
Playable = 1
ModFolder = UltimateApocalypse_THB_test
ModVersion = 1.89.55d
TextureFE = Art/UI/Textures/Title_winter_assault.tga
TextureIcon =
RuntimeMode = 3

DataFolder.1 = Data

RequiredMod.1 = DXP3
RequiredMod.2 = DXP2
RequiredMod.3 = WXP
RequiredMod.4 = W40k
RequiredMod.5 = Tyranids_Art






